name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [lint, stylelint]

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Nx set SHAs
        uses: nrwl/nx-set-shas@v5

      - name: Run Nx affected (PR)
        if: github.event_name == 'pull_request'
        run: >
          pnpx nx affected
          --target=${{ matrix.target }}

      - name: Run Nx affected (push)
        if: github.event_name == 'push'
        run: >
          pnpx nx affected
          --target=${{ matrix.target }}
